server:
  servlet:
    #服务路径
    context-path: /jshERP-boot
    session:
      #登录超时-秒
      timeout: 36000
    #文件上传限制(byte)
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760
  port: 9888
  #文件上传临时路径
  tomcat:
    basedir: /opt/tmp/tomcat


# mysql数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jsh_erp?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: hsp
    driver-class-name: com.mysql.jdbc.Driver
  # Redis
  redis:
    host: 192.168.66.131
    port: 6379
    password: 1234abcd

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleteFlag

#租户对应的角色id
manage:
  roleId: 10
#租户允许创建的用户数
tenant:
  userNumLimit: 1000000
#租户允许试用的天数
  tryDayLimit: 3000
#插件配置
plugin:
  runMode: prod
  pluginPath: plugins
  pluginConfigFilePath: pluginConfig
#文件上传根目录
file:
  path: /opt/jshERP/upload

